<?php

function thf_fields_theme($existing, $type, $theme, $path) {
  return [
    'input__number__react' => [
      'base hook' => 'input',
    ]
  ];
}

function thf_fields_preprocess_input(&$variables) {
  if ($variables['theme_hook_original'] == 'input__number__react') {
    $variables['attributes']['prefix'] = isset($variables['element']['#react_prefix']) ? $variables['element']['#react_prefix'] : FALSE;
    $variables['attributes']['suffix'] = isset($variables['element']['#react_suffix']) ? $variables['element']['#react_suffix'] : FALSE;
    // ksm($variables);
    // $variables['#attached']['drupalSettings']['react-fields'][] = $variables['attributes'];
  }
}
